# Generated by Django 2.2.3 on 2019-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
